
replicaCount: 1

image:
  baserepository: image-registry.openshift-image-registry.svc:5000
  repository: aa
  tag: ""
  baseimage: 'nodejs-18'
  baseimagetag: 'latest'
  baseimagerepo: registry.access.redhat.com/ubi9
  createbaseimage: true

nameOverride: ""
fullnameOverride: ""
runbuild: true

podAnnotations:
  sidecar.istio.io/inject: 'true'

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: '2'
    memory: 5G
  requests:
    cpu: 10m
    memory: 50m

repo: 'https://github.com/casimon-rh/gs-nodejs-demo2'

environment:
- name: CHAIN_SVC
  value: 'http://bb-mesh-element:3000/chain'
- name: ID
  value: A
- name: NEXT_SVC
  value: 'http://bb-mesh-element:3000'
- name: JUMPS
  value: '12'

wildcard: apps.cluster-7fldg.7fldg.sandbox1150.opentlc.com

servicemesh:
  create: false
  gateway:
    create: false
  subsets: []